# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J3+lHv/RdaHBXOXERsA9JEM+ibqK65y8yBuzvtadvH87ABFjdLav2MMK3T7V08G7/QFEHZJy/rJXBZOwzSiVnivxaSk+1q+FxTwWpIU6/LHK0B4cXNez27s4aD+e6GLqNDEi3Wbcsgrb4eC3L7JDUakqCH5h9p+T6l3K9qWsFf9VnlDDo4cK73ccY0LNGFrd2v8LpgVumUEVIwWgq5IfnP/Xm+VH3ZKv17M0Of9CqqI7qDy2rnXybp3coYJiT120rY7SpkajzWBnkTRCDcdy+wflb1cqGu/+7+XnxCf2eQfHZNL91bl8NiTjUS2hONImy9Iu2Y1HXc3fY9tSR/krX2sEfGplq4CseGPXQl9cV287VJrh/4yR1aA3KqkM4K28BJGbhu2wpGCLyk5MLblTUCcSKv2+qN93yaJtD5TOmgEzSOxBsHc5sqBK1wjCHMcnDGXVtDIe4n7npoPANdWT/wdsOmWouKpPlCjqwwFl+HmsQjkXZms0hE3WY1r/OAD4PhbioayG0TGaRNyEmNZiMUX9LkIpMvPf0xqF8ozIH8SdAPilZC3sh94qITEtpm2icosIWPDFyZ3aoitfNKhWx3fPwO+TaO2FGPElHydE78Gjx2NhL5yDvmp7jyyciqt28sK7oLa5i/lZX5e+1Qj9dxGLENYSFeQ/LcXXrSfNx84="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
