travis:
  secure:
    BINSTAR_TOKEN: xU8Hoemaw0GRV7Lh9Om1oZdssNq3F+ISzaSQIZij2z5SWapg/tPIJIP2IoPi7/qLRw9EAfBix1kMd/B7HraCsIbi/5BeNkKF/miB9zTvZelhShdF8fFoj261yzHazYbs32L/4vG2MnjJhkY6L50T2so6N5PYh9n1f4AqD3AY94HAbMgdr/njGIIVltVIwCB60kxlN2w9AiMDhporCOy6bzAiv2QNqyA6oC4cJm5XBY6pMYB81xgDpOtZTHQ2doJ3tKG8ECuqYOOfRddrgQ80h9YuFqz2FXFCBk7jXJQavEaAq3JIDkeJmVsQVDe4bVwWUEsamjOPUnJQDPQ9ljscjckV8YQ88lTAyi8AD+GnxZFVEaGo0D4j9TYrpNV3BMjW7yTchJ4rPvCnW7MBFa413Q+fofhIWX1e/71w9H2JI6VMEnNwRtb9XCWKe3m84vab+6SfrmxR33S5dF047+Q6bevWPiF1RzKDhmm4xvBwOVkdiihTv7RE6w9DQ3+JN42seEJxKJexabMse42TWAdlSiAOd1MZXwy75SJqdec39Cp7et3ArbBWi/22nrijwKR+3zDoLp9kuyyTmkbu4rv4zzPGG5YMq953GwggJz/L5H6S/rp6kuqN0R5VVN9Ao/tNX/pRNNaCGhxtMoZny+g+Zy2l+q2hfgCmiub1+E0tDoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
