travis:
  secure:
    BINSTAR_TOKEN: ibGnL+07shEIhcfIA/K6aEXYT53gC82Vjt76v+P5lK2dRb/e5j3Z17eD5mM3eRSCT9hSszElJNQtRfIK72bPsP4C3CeADwMSVqIQcA+vbguYSIL+eGXS1JnwtF7utIYld8v5UScXv28MytyCIfISg5ppAhu538tSWqyvSQ5KV9PurcN8W/+yZMxs8BoYEethvpKTcIsedemdxPZ1ARQaMAsuhuzBmOrmrsIByKv/bMjY9upH6zKFqoz8znJBU9rYlls7u3AHUVgKPalRBGvMhCmbPDL+Juj4dTBDf+MdrL8JLSmLqQ5xyO/aRDAYqyvhBXAbTNCtWvOjHHXchFT0xCIXxYrhrpl0iCVAVNdzcF5Y5/Dx8t0xs4e/7++J+uOHOBPb+K0IE9OUPGXMZBxQWdZLh3xav0vJYast5FL75opyfkHDz6wiDGlN7Lm6mbn3B/KFutyTemS5grVt49HYMyb3vlvyqLAmtkDJc8jXK5nqor37UW8Iz93Vd8EGk3KSyr1RaEeomLNiW6yki4xETk3/SsL7Fx/BlSQfC3jaUxrINK9VpuIGfYefAEwUygMLn7Q3qQzlUZWJoYm8YUiZsR/xD41i7dLB3QvqFNM1hpIQGm73a98UplcEvO4MRfOWljgvxe0hDsrSShQYxRUaQM//KuW7ZuNE9uC+Aj/78FE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
