travis:
  secure:
    BINSTAR_TOKEN: smbPwyi6gcLS6ajE2aAeDk2ah+5mCFRVMtZvucqa4W7CJwNDoXUp6aEO1EOfiQy0vT8+91pFCqsypR6PeI6SO0Wylo+TrEm0WZJIjELfgOoC0yd2MpBWjg8ASNOhi/qx5bCTSb0m3fpBQL8v5jrBoAGwZA//jxap+iLbXG22zgikVIrMolJe5w0SguTkkwDJKrj1UzA/qAaQPI4LO1JzUyidev+FPl3oQVsS2xnxXh4Oudy/rA8mQB9Q0SqObqtU14jE0MPY9LGRScz53WmtLUseOwiIN7oA4d94/VGBCD+5cxocXz44TZPl8H1nTvptw/+CyBf17QCU2ZkmJ0gAXCL2ae3xmOUZVep5IlXpnD0+NhIoDHoD42kJ6R91q64hAbeFYwZb4IiCsm+bNXAmyQY/VPY6A3NWZ1O5lWYMfb4R5omz3QlJxMIRM1dXxDtlX03B0bRYKSGWTvK4X8dJpBt4v1gjvIeFHM0R1oxVVDX5iZMR8x0X33pmoZXvva4jyLVhg4ZmesA358r9vuphweDi0clxedsDXVSQHefDWEQigZ08gtHAWVa/iURjdc00foA2AkI9cQYRhXGwfMdLVs980CKzS3OjqwvN65Zp051W0B5PDyTJIi/UMfX8GSHKM6bYCFFl5YUMJLgsd7p5qgQbT0R3FE1fO195TW5r5dc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
