travis:
  secure:
    BINSTAR_TOKEN: J3+lHv/RdaHBXOXERsA9JEM+ibqK65y8yBuzvtadvH87ABFjdLav2MMK3T7V08G7/QFEHZJy/rJXBZOwzSiVnivxaSk+1q+FxTwWpIU6/LHK0B4cXNez27s4aD+e6GLqNDEi3Wbcsgrb4eC3L7JDUakqCH5h9p+T6l3K9qWsFf9VnlDDo4cK73ccY0LNGFrd2v8LpgVumUEVIwWgq5IfnP/Xm+VH3ZKv17M0Of9CqqI7qDy2rnXybp3coYJiT120rY7SpkajzWBnkTRCDcdy+wflb1cqGu/+7+XnxCf2eQfHZNL91bl8NiTjUS2hONImy9Iu2Y1HXc3fY9tSR/krX2sEfGplq4CseGPXQl9cV287VJrh/4yR1aA3KqkM4K28BJGbhu2wpGCLyk5MLblTUCcSKv2+qN93yaJtD5TOmgEzSOxBsHc5sqBK1wjCHMcnDGXVtDIe4n7npoPANdWT/wdsOmWouKpPlCjqwwFl+HmsQjkXZms0hE3WY1r/OAD4PhbioayG0TGaRNyEmNZiMUX9LkIpMvPf0xqF8ozIH8SdAPilZC3sh94qITEtpm2icosIWPDFyZ3aoitfNKhWx3fPwO+TaO2FGPElHydE78Gjx2NhL5yDvmp7jyyciqt28sK7oLa5i/lZX5e+1Qj9dxGLENYSFeQ/LcXXrSfNx84=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
